# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  pull_request:
  push:
    branches:
      - master

name: "Validate"

jobs:
  composer-validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: mbstring
          php-version: 8.3

      - run: composer validate --strict

  static-code-analysis:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.3"
          - "8.4"
        dependencies:
          - lowest
          - highest

    steps:
      - uses: actions/checkout@master

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: mbstring
          php-version: "${{ matrix.php-version }}"

      - uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - run: vendor/bin/phpstan analyse --configuration=phpstan.neon
