# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  pull_request:
  push:
    branches:
      - master

name: "Validate"

jobs:
  composer-validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: mbstring
          php-version: 8.1

      - run: composer validate --strict

  static-code-analysis:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
        dependencies:
          - lowest
          - highest

    steps:
      - uses: actions/checkout@master

      - uses: shivammathur/setup-php@v2
        with:
          coverage: none
          extensions: mbstring
          php-version: "${{ matrix.php-version }}"

      - if: matrix.dependencies == 'lowest'
        run: composer update --prefer-lowest --no-interaction --no-progress --no-suggest

      - if: matrix.dependencies == 'highest'
        run: composer update --no-interaction --no-progress --no-suggest

      - run: vendor/bin/phpstan analyse
